# Generated by Django 5.0.12 on 2025-12-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField(help_text='ID of the job position')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=255)),
                ('grad_year', models.IntegerField()),
                ('cgpa', models.CharField(max_length=50)),
                ('work_status', models.CharField(choices=[('Fresher', 'Fresher'), ('Experienced', 'Experienced')], default='Fresher', max_length=20)),
                ('current_company', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('experience_years', models.CharField(blank=True, max_length=50, null=True)),
                ('current_ctc', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_ctc', models.CharField(blank=True, max_length=50, null=True)),
                ('notice_period', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('resume_url', models.URLField(max_length=500)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
