# Generated by Django 5.0.12 on 2025-12-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doubts',
            fields=[
                ('doubtid', models.AutoField(db_column='doubtId', primary_key=True, serialize=False)),
                ('doubttext', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='doubtText')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doubts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('solutionid', models.AutoField(db_column='solutionId', primary_key=True, serialize=False)),
                ('solution', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'solutions',
                'managed': False,
            },
        ),
    ]
