# Generated by Django 5.0.12 on 2025-12-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Createjob',
            fields=[
                ('jobid', models.AutoField(db_column='jobId', primary_key=True, serialize=False)),
                ('jobtitle', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='jobTitle', max_length=255, null=True)),
                ('job_type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
                ('reqexp', models.IntegerField(blank=True, null=True)),
                ('company', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('location', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('from_passed_out_year', models.IntegerField(blank=True, null=True)),
                ('to_passed_out_year', models.IntegerField(blank=True, null=True)),
                ('hr_phone', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('hr_email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('job_description', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('apply_before_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('posteddate', models.DateTimeField(blank=True, db_column='postedDate', null=True)),
            ],
            options={
                'db_table': 'createjob',
                'managed': False,
            },
        ),
    ]
