# Generated by Django 5.0.12 on 2025-12-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
