# Generated by Django 5.0.12 on 2025-12-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempts',
            fields=[
                ('attemptid', models.AutoField(db_column='attemptId', primary_key=True, serialize=False)),
                ('attemptdate', models.DateTimeField(blank=True, db_column='attemptDate', null=True)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ai_evaluated', models.BooleanField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exam_attempts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExamBatches',
            fields=[
                ('exambatchid', models.AutoField(db_column='examBatchId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'exam_batches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExamResults',
            fields=[
                ('resultid', models.AutoField(db_column='resultId', primary_key=True, serialize=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_mcq_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_descriptive_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_coding_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exam_results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('examid', models.AutoField(db_column='examId', primary_key=True, serialize=False)),
                ('examname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='examName', max_length=100, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('optionid', models.AutoField(db_column='optionId', primary_key=True, serialize=False)),
                ('optiontext', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='optionText', max_length=500, null=True)),
                ('iscorrect', models.BooleanField(blank=True, db_column='isCorrect', null=True)),
            ],
            options={
                'db_table': 'options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('questionid', models.AutoField(db_column='questionId', primary_key=True, serialize=False)),
                ('questiontext', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionTypes',
            fields=[
                ('questiontypeid', models.AutoField(db_column='questionTypeId', primary_key=True, serialize=False)),
                ('typename', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='typeName', max_length=50)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'question_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentAnswers',
            fields=[
                ('studentanswerid', models.AutoField(db_column='studentAnswerId', primary_key=True, serialize=False)),
                ('descriptive_answer', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('code_answer', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_feedback', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('evaluated', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('points_earned', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'student_answers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentBatches',
            fields=[
                ('studentbatchid', models.AutoField(db_column='studentBatchId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'student_batches',
                'managed': False,
            },
        ),
    ]
