# Generated by Django 5.0.12 on 2025-12-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Lecture Note', 'Lecture Note'), ('Lab Manual', 'Lab Manual'), ('Assignment', 'Assignment'), ('Question Paper', 'Question Paper')], default='Lecture Note', max_length=50)),
                ('subject', models.CharField(help_text='Ex: Data Structures, OS, Maths', max_length=100)),
                ('pdf_url', models.URLField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
