# Generated by Django 5.0 on 2026-01-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('zoom_meeting_id', models.CharField(max_length=50)),
                ('start_url', models.TextField()),
                ('join_url', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('recording_url', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
