# Generated by Django 5.0.12 on 2025-12-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('batchid', models.AutoField(db_column='batchId', primary_key=True, serialize=False)),
                ('batchname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='batchName', max_length=100)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'batches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentBatches',
            fields=[
                ('studentbatchid', models.AutoField(db_column='studentBatchId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'student_batches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrainerBatches',
            fields=[
                ('trainerbatchid', models.AutoField(db_column='trainerBatchId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'trainer_batches',
                'managed': False,
            },
        ),
    ]
