# Generated by Django 5.0.12 on 2025-12-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('contentid', models.AutoField(db_column='contentId', primary_key=True, serialize=False)),
                ('contentname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='contentName', max_length=255, null=True)),
                ('contenturl', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='contentUrl', max_length=500)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseid', models.AutoField(db_column='courseId', primary_key=True, serialize=False)),
                ('coursename', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='courseName', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseSubjects',
            fields=[
                ('coursesubjectid', models.AutoField(db_column='courseSubjectId', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'course_subjects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subjectid', models.AutoField(db_column='subjectId', primary_key=True, serialize=False)),
                ('subjectname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='subjectName', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subjects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemSetups',
            fields=[
                ('setupid', models.AutoField(db_column='setupId', primary_key=True, serialize=False)),
                ('setupname', models.CharField(db_column='setupName', max_length=100)),
                ('setupdescription', models.TextField(blank=True, db_column='setupDescription', null=True)),
                ('setupurl', models.CharField(blank=True, db_column='setupUrl', max_length=255, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'system_setups',
                'managed': False,
            },
        ),
    ]
