# Generated by Django 5.0.12 on 2025-12-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectsTopicswiseQuestions',
            fields=[
                ('topicquestionid', models.AutoField(db_column='topicQuestionId', primary_key=True, serialize=False)),
                ('topicname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='topicName', max_length=100)),
                ('practice_questions_url', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subjects_topicswise_questions',
                'managed': False,
            },
        ),
    ]
