# Generated by Django 5.0.12 on 2026-04-12 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_by', models.CharField(blank=True, db_column='created_by', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'announcements',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementBatches',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('announcement', models.ForeignKey(db_column='announcement_id', on_delete=django.db.models.deletion.DO_NOTHING, to='announcements.announcement')),
                ('batch', models.ForeignKey(db_column='batchId', on_delete=django.db.models.deletion.DO_NOTHING, to='batches.batches')),
            ],
            options={
                'db_table': 'announcement_batches',
            },
        ),
    ]
