# Generated by Django 5.0.12 on 2025-12-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationInfo',
            fields=[
                ('educationid', models.AutoField(db_column='educationId', primary_key=True, serialize=False)),
                ('qualification_type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('qualification', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
                ('joined_on', models.DateField(blank=True, null=True)),
                ('left_on', models.DateField(blank=True, null=True)),
                ('marks', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('marking_system', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('university', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
            ],
            options={
                'db_table': 'education_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('experienceid', models.AutoField(db_column='experienceId', primary_key=True, serialize=False)),
                ('position', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
                ('company', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
                ('joined_on', models.DateField(blank=True, null=True)),
                ('left_on', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
            ],
            options={
                'db_table': 'experience',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Expwork',
            fields=[
                ('expworkid', models.AutoField(db_column='expWorkId', primary_key=True, serialize=False)),
                ('worked_on', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
            ],
            options={
                'db_table': 'expwork',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('personalid', models.AutoField(db_column='personalId', primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='firstName', max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='lastName', max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('linkedinid', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='linkedinId', max_length=255, null=True)),
                ('githubid', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='githubId', max_length=255, null=True)),
            ],
            options={
                'db_table': 'personal_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProficiencyLevels',
            fields=[
                ('proficiencyid', models.AutoField(db_column='proficiencyId', primary_key=True, serialize=False)),
                ('levelname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='levelName', max_length=50)),
            ],
            options={
                'db_table': 'proficiency_levels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectDescriptions',
            fields=[
                ('projectdescid', models.AutoField(db_column='projectDescId', primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
            ],
            options={
                'db_table': 'project_descriptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('projectid', models.AutoField(db_column='projectId', primary_key=True, serialize=False)),
                ('projectname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='projectName', max_length=255, null=True)),
                ('githublink', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='githubLink', max_length=255, null=True)),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectTechStack',
            fields=[
                ('projecttechid', models.AutoField(db_column='projectTechId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'project_tech_stack',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SkillCategories',
            fields=[
                ('categoryid', models.AutoField(db_column='categoryId', primary_key=True, serialize=False)),
                ('categoryname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='categoryName', max_length=100)),
            ],
            options={
                'db_table': 'skill_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SkillsInfo',
            fields=[
                ('skillinfoid', models.AutoField(db_column='skillInfoId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'skills_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SkillsMaster',
            fields=[
                ('skillmasterid', models.AutoField(db_column='skillMasterId', primary_key=True, serialize=False)),
                ('skillname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='skillName', max_length=100)),
            ],
            options={
                'db_table': 'skills_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('tech_stackid', models.AutoField(db_column='tech_stackId', primary_key=True, serialize=False)),
                ('techname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='techName', max_length=100)),
            ],
            options={
                'db_table': 'tech_stack',
                'managed': False,
            },
        ),
    ]
